export const MOCK_CUSTOMERS = [
  {
    id: 1,
    nombres: "Juan",
    apellidos: "García López",
    empresa: "Tech Solutions",
    celular: "3001234567",
    password: "hashed_password_1",
    edad: 32,
    email: "juan.garcia@example.com",
    sexo: "M",
    medio_ingreso: "Google",
    registro: "Pag Web",
    tipo_documento: "CC",
    numero_documento: "1023456789",
    estado: 1,
    antiguo: 0,
    puntuacion: 85,
    created_at: "2024-01-15",
    updated_at: "2024-01-15",
  },
  {
    id: 2,
    nombres: "María",
    apellidos: "Rodríguez Martínez",
    empresa: "Digital Marketing Pro",
    celular: "3101234568",
    password: "hashed_password_2",
    edad: 28,
    email: "maria.rodriguez@example.com",
    sexo: "F",
    medio_ingreso: "Facebook",
    registro: "Sistema",
    tipo_documento: "CC",
    numero_documento: "1023456790",
    estado: 1,
    antiguo: 0,
    puntuacion: 92,
    created_at: "2024-01-14",
    updated_at: "2024-01-14",
  },
  {
    id: 3,
    nombres: "Carlos",
    apellidos: "Hernández Pérez",
    empresa: "Construcciones HS",
    celular: "3201234569",
    password: "hashed_password_3",
    edad: 45,
    email: "carlos.hernandez@example.com",
    sexo: "M",
    medio_ingreso: "WhatsApp",
    registro: "Pag Web",
    tipo_documento: "CC",
    numero_documento: "1023456791",
    estado: 1,
    antiguo: 1,
    puntuacion: 78,
    created_at: "2023-12-10",
    updated_at: "2024-01-10",
  },
  {
    id: 4,
    nombres: "Laura",
    apellidos: "López García",
    empresa: "E-Commerce Plus",
    celular: "3301234570",
    password: "hashed_password_4",
    edad: 31,
    email: "laura.lopez@example.com",
    sexo: "F",
    medio_ingreso: "Instagram",
    registro: "Sistema",
    tipo_documento: "CC",
    numero_documento: "1023456792",
    estado: 1,
    antiguo: 0,
    puntuacion: 88,
    created_at: "2024-01-12",
    updated_at: "2024-01-12",
  },
  {
    id: 5,
    nombres: "Roberto",
    apellidos: "Sánchez Molina",
    empresa: "Consultoría Empresarial",
    celular: "3401234571",
    password: "hashed_password_5",
    edad: 52,
    email: "roberto.sanchez@example.com",
    sexo: "M",
    medio_ingreso: "Referencia",
    registro: "Pag Web",
    tipo_documento: "CC",
    numero_documento: "1023456793",
    estado: 1,
    antiguo: 1,
    puntuacion: 95,
    created_at: "2023-11-20",
    updated_at: "2024-01-05",
  },
  {
    id: 6,
    nombres: "Sofía",
    apellidos: "Torres Jiménez",
    empresa: "Agencia Creativa",
    celular: "3501234572",
    password: "hashed_password_6",
    edad: 26,
    email: "sofia.torres@example.com",
    sexo: "F",
    medio_ingreso: "Google",
    registro: "Sistema",
    tipo_documento: "CC",
    numero_documento: "1023456794",
    estado: 1,
    antiguo: 0,
    puntuacion: 82,
    created_at: "2024-01-11",
    updated_at: "2024-01-11",
  },
  {
    id: 7,
    nombres: "Diego",
    apellidos: "Flores Méndez",
    empresa: "Soluciones IT",
    celular: "3601234573",
    password: "hashed_password_7",
    edad: 36,
    email: "diego.flores@example.com",
    sexo: "M",
    medio_ingreso: "Facebook",
    registro: "Pag Web",
    tipo_documento: "CC",
    numero_documento: "1023456795",
    estado: 1,
    antiguo: 0,
    puntuacion: 87,
    created_at: "2024-01-13",
    updated_at: "2024-01-13",
  },
  {
    id: 8,
    nombres: "Patricia",
    apellidos: "Ruiz Acosta",
    empresa: "Servicios Contables",
    celular: "3701234574",
    password: "hashed_password_8",
    edad: 48,
    email: "patricia.ruiz@example.com",
    sexo: "F",
    medio_ingreso: "WhatsApp",
    registro: "Sistema",
    tipo_documento: "CC",
    numero_documento: "1023456796",
    estado: 1,
    antiguo: 1,
    puntuacion: 91,
    created_at: "2023-10-15",
    updated_at: "2024-01-08",
  },
  {
    id: 9,
    nombres: "Miguel",
    apellidos: "Cervantes Silva",
    empresa: "Transportes Rapidos",
    celular: "3801234575",
    password: "hashed_password_9",
    edad: 41,
    email: "miguel.cervantes@example.com",
    sexo: "M",
    medio_ingreso: "Instagram",
    registro: "Pag Web",
    tipo_documento: "CC",
    numero_documento: "1023456797",
    estado: 1,
    antiguo: 1,
    puntuacion: 79,
    created_at: "2023-12-05",
    updated_at: "2024-01-09",
  },
  {
    id: 10,
    nombres: "Valentina",
    apellidos: "Moreno Castillo",
    empresa: "Boutique Exclusiva",
    celular: "3901234576",
    password: "hashed_password_10",
    edad: 29,
    email: "valentina.moreno@example.com",
    sexo: "F",
    medio_ingreso: "Referencia",
    registro: "Sistema",
    tipo_documento: "CC",
    numero_documento: "1023456798",
    estado: 1,
    antiguo: 0,
    puntuacion: 93,
    created_at: "2024-01-10",
    updated_at: "2024-01-10",
  },
  {
    id: 11,
    nombres: "Fernando",
    apellidos: "Gómez Navarro",
    empresa: "Restaurante Premium",
    celular: "3911234577",
    password: "hashed_password_11",
    edad: 55,
    email: "fernando.gomez@example.com",
    sexo: "M",
    medio_ingreso: "Google",
    registro: "Pag Web",
    tipo_documento: "CC",
    numero_documento: "1023456799",
    estado: 1,
    antiguo: 1,
    puntuacion: 86,
    created_at: "2023-09-20",
    updated_at: "2024-01-07",
  },
  {
    id: 12,
    nombres: "Beatriz",
    apellidos: "Vargas Delgado",
    empresa: "Clinica Dental",
    celular: "3921234578",
    password: "hashed_password_12",
    edad: 38,
    email: "beatriz.vargas@example.com",
    sexo: "F",
    medio_ingreso: "Facebook",
    registro: "Sistema",
    tipo_documento: "CC",
    numero_documento: "1023456800",
    estado: 1,
    antiguo: 0,
    puntuacion: 89,
    created_at: "2024-01-09",
    updated_at: "2024-01-09",
  },
];
